### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by AverageDood** [AHilyard/Iceberg#12]
**Describe the bug**
This bug triggers on two scenarios:
1.- Have Iceberg, Player Animator and a mod that depends on Iceberg (this specific case: Advancement Plaques)
2.- Have Iceberg, Player Animator and a mod that depends on Player Animator (this specific case, both Combat Roll and Better combat)

For some reason, simply having Player Animator and Iceberg together, without mods that may depend on them, causes no problem and the game launches without trouble.

Iceberg simply prevents the game from launching, and the launcher complains about mixin, specifically, how one of them at Iceberg tried to load too early.

**To Reproduce**
1. Have Iceberg, Player Animator and a mod that depends on either of them
2. Try to launch the game
3. Profitn't

**Expected behavior**
Minecraft should launch and run without crashing

**Environment (please complete the following information):**
 - Mod name: Iceberg
 - Mod version: 1.0.47
 - Modloader: Forge
 - Modloader version: 43.1.30
 - Minecraft version: 1.19.2

**Log files**
Player Animation dependant: https://mclo.gs/erBeGqu
Iceberg dependant: https://mclo.gs/cg8Jpd7

Edit: correct the submission, as I accidentally sent it while redacting.

**Comment by AverageDood** [comment]
I'm gonna be closing this issue, as I double checked the dependencies. I thought Configured depended on this mod, and not the other way around. After installing Configured and Catalogue, everything works as it should.

Sorry for the inconvenience

**Comment by AHilyard** [comment]
Ah okay, I'm glad you were able to sort that out!

**Comment by AverageDood** [comment]
Please don't kill me now...

I use a third party launcher, mod pack manager, PolyMC.

Well, turns out that when I installed Configured and Catalogue, Iceberg was actually disabled and I have just realized this. Kinda feel like an idiot

**Comment by AHilyard** [comment]
No worries, an honest mistake.  :)
