### ISSUE TITLE
Update to 1.19.3

### ISSUE THREAD

**Issue by GhostIsBeHere** [AHilyard/Iceberg#14]
**Describe the bug**
~~Crashes when launching on 1.19.3~~
1.19.3 is not marked as incompatible

**To Reproduce**
1. Make fabric instance with iceberg and fabric api
2. Crash

**Expected behavior**
Not crash

**Environment (please complete the following information):**
 - Mod name: Iceberg
 - Mod version: 1.0.46
 - Modloader: Fabric
 - Modloader version: Fabric 0.14.11, Fabric API 0.69.1
 - Minecraft version: 1.19.3

**Log files**
[Log](https://paste.atlauncher.com/view/d9a58049-2195-4eb7-96da-46a2efaaa09d)

**Comment by AHilyard** [comment]
There is no version currently compatible with 1.19.3.  It will be released in the coming days.

**Comment by dreit-p** [comment]
Hey @AHilyard , can you update Fabric version too?

**Comment by Caerot** [comment]
When will this be updated to 1.19.3?

**Comment by wolvyreen** [comment]
ouch!  what happened to releasing the 1.19.3 in the coming days?  This was last month already.

**Comment by AHilyard** [comment]
I have finished the 1.19.3 version for Fabric, it will be available on CurseForge once it is processed/approved.

**Comment by dreit-p** [comment]
@AHilyard
Thank you very much!

**Comment by wolvyreen** [comment]
Thank you so much!! The community needs more Devs that respond like you!!  Well done and thank you.
