### ISSUE TITLE
Fabric 1.19.3 Crash

### ISSUE THREAD

**Issue by ProfLS** [AHilyard/Iceberg#18]
Consistent crashing on 1.19.3

A bunch of mixin errors..

possible fix:  
1.19.3 Fabric release changed some class names under the hood.. esp affected api makers.. maybe try to update those accordingly?

**Comment by muluffel** [comment]
Maybe the isues exist because there is no Iceberg release for 1.19.3?

**Comment by AHilyard** [comment]
@muluffel Is correct, as of the time of creating this issue, there was no 1.19.3 version available for Fabric.  CurseForge lists supported versions for each file for future reference.

Fortunately I've just finished and uploaded a compatible 1.19.3 version for Fabric, which will be available once it is processed by CurseForge.

**Comment by ProfLS** [comment]
Thanks man! I love your work btw :)
