### ISSUE TITLE
Installed with Weapon Master pressing left shift will cause the game to crash

### ISSUE THREAD

**Issue by nulleqn** [AHilyard/Iceberg#19]
[latest.txt](https://github.com/AHilyard/Iceberg/files/10569941/latest.txt)

[debug.txt](https://github.com/AHilyard/Iceberg/files/10569964/debug.txt)

**Comment by AHilyard** [comment]
Could you post your mod list so I can try to recreate this crash?

**Comment by nulleqn** [comment]
yes sir
[minecraft-exported-logs-2023-01-31T18-50-07.log](https://github.com/AHilyard/Iceberg/files/10574801/minecraft-exported-logs-2023-01-31T18-50-07.log)
