### ISSUE TITLE
Incompatible with Industrial Revolution

### ISSUE THREAD

**Issue by StarskyXIII** [AHilyard/Iceberg#2]
Minecraft Version: 1.18.1
Fabric loader: 0.12.12
Iceberg: fabric-1.0.37
Industrial Revolution: 1.13.4-BETA

When I scrolling in Industrial Revolution's Creative Tab, game crash.

Crash Report:
https://drive.google.com/file/d/1eGYDs5TUi8icuecmhjgZgQQaVBjCFLm3/view?usp=sharing

**Comment by wackoamd1** [comment]
not just creative , 
exactly the same versions as above
when u point at a IR machine in inventory the game client crashes.
https://paste.ee/p/5mpsy

**Comment by AHilyard** [comment]
Thank you for the report, this has been fixed in the most recent release (1.0.38).  Feel free to reopen if you have issues with that version.
