### ISSUE TITLE
Incompatible with Quilt

### ISSUE THREAD

**Issue by Treetrain1** [AHilyard/Iceberg#26]
In the method `VertexCollector.create()`, Iceberg uses Fabric's `VersionPredicateParser.parse()` instead of the api `VersionPredicate.parse()`. This causes an incompatibility with Quilt.

I believe this issue is present in the branches `1.19.3-fabric` and `1.19.4-fabric`

Minecraft 1.19.4
Quilt Loader 0.18.10
Quilted Fabric API 6.0.0-beta.6+0.79.0-1.19.4
Iceberg 1.1.8

Legendary Tooltips has been used as an example cause of the crash, although the actual bug is in Iceberg, as said above.

Logs can be found here
https://mclo.gs/62Y3bm0

## How to fix
1. Go to com/anthonyhilyard/iceberg/renderer/VertexCollector.java
2. In the `create()` method, change `useSodiumVersion` to use `VersionPredicate.parse()` instead of `VersionPredicateParser.parse()`
3. done

**Comment by AHilyard** [comment]
Thank you for the helpful information.  I've made this change in the latest version of Iceberg (1.1.10).
