### ISSUE TITLE
Crashing after updating to forge 1.19.4 - 45.0.64

### ISSUE THREAD

**Issue by MrKashew** [AHilyard/Iceberg#29]
[debug.log](https://github.com/AHilyard/Iceberg/files/11524146/debug.log)

[latest.log](https://github.com/AHilyard/Iceberg/files/11524147/latest.log)

**Comment by ffuentesm** [comment]
Same error here, it works on forge 45.0.63, but now the new one. 
The error says something about item tooltip injection fail

**Comment by MrKashew** [comment]
Did not work on .63 for me but did work on .59 for me

**Comment by AHilyard** [comment]
Thanks for the head's up everyone, this has been fixed in the latest version of Iceberg. 😄
