### ISSUE TITLE
Iceberg 1.0.37 still causes tooltip conflict with Botania

### ISSUE THREAD

**Issue by Xastabus** [AHilyard/Iceberg#3]
Minecraft 1.18.1
Fabric 0.12.12
Iceberg 1.0.35 - 1.0.37
+ many other mods

Tooltip conflicts persisting through Iceberg 1.0.37.  Rolling back to Iceberg 1.0.27 fixes the issue for me.

[crash-2022-01-07_09.56.57-client.txt](https://github.com/AHilyard/Iceberg/files/7829510/crash-2022-01-07_09.56.57-client.txt)

The crash happens when a player mouseovers a Mana Tablet from Botania.

**Comment by Xastabus** [comment]
The Mana Tablet and several other items in Botania add a mana bar to the item tooltip.

![2022-01-07_12 06 23](https://user-images.githubusercontent.com/1816386/148580527-3f624a30-9040-437d-a7ad-8c50c8bb4325.png)

**Comment by AHilyard** [comment]
Thank you for the report, the log and screenshot were very helpful in tracking this down.  This has now been fixed in the most recent release (1.0.38).  Feel free to reopen if you have issues with that version.
