### ISSUE TITLE
Random crash with a quark

### ISSUE THREAD

**Issue by BlackAures1** [AHilyard/Iceberg#30]
When I tried to open the menu in creative mode and hover over the enchanted book, the game stopped and crashed. This is the first time such an error has appeared. The crashreport description mentions your library and quark.
[crash-2023-05-24_23.14.08-client.txt](https://github.com/AHilyard/Iceberg/files/11558735/crash-2023-05-24_23.14.08-client.txt)

**Comment by AHilyard** [comment]
Closing this as the crash has been fixed (https://github.com/VazkiiMods/Quark/issues/4204).
