### ISSUE TITLE
1.19.4 Fabric Crashed with Sodium

### ISSUE THREAD

**Issue by Faivonisme** [AHilyard/Iceberg#33]
I can't understand the crash log fully but it did indeed says Iceberg crashed with Sodium. The other mods that uses Iceberg are Advancement Plagues and Legendary Tooltips. 
Is there a fix to this or? 
[crash-2023-05-31_16.15.16-client.txt](https://github.com/AHilyard/Iceberg/files/11611071/crash-2023-05-31_16.15.16-client.txt)

**Comment by QueenUlyana** [comment]
Seconded. @AHilyard

**Comment by griffin4cats** [comment]
Thirded.
I assume this happens when the game attempts to render the spinning model of the item.

**Comment by AHilyard** [comment]
Iceberg version 1.1.10 has been archived due to this issue, please revert to 1.1.9.  See this issue for more info: https://github.com/AHilyard/LegendaryTooltips/issues/72
