### ISSUE TITLE
Crash Game 1.19.4 Fabric

### ISSUE THREAD

**Issue by QueenUlyana** [AHilyard/Iceberg#34]
As soon as I try to search for "Elytra", the game closes immediately.
@AHilyard 
[999.txt](https://github.com/AHilyard/Iceberg/files/11642059/999.txt)

There is some kind of conflict going on between Iceberg and Sodium. 
### **It wasn't like this before, but it appeared after the Iceberg update.**

**Comment by QueenUlyana** [comment]
### **_By the way, I use Iceberg-1.19.4-fabric-1.1.10.jar_**

**Comment by QueenUlyana** [comment]
I put Iceberg-1.19.4-fabric-1.1.9.jar instead of Iceberg-1.19.4-fabric-1.1.10.jar. All crashes are gone, errors in logs are gone too.

**Comment by AHilyard** [comment]
Iceberg 1.1.10 has been archived because of this issue, 1.1.9 is the proper version to use for now.
