### ISSUE TITLE
Exit Code 1 on 1.19.4 (Forge)

### ISSUE THREAD

**Issue by Devilswarchild** [AHilyard/Iceberg#35]
updated to the latest version (Iceberg-1.19.4-forge-1.1.10.jar) and was presented with the exit code 1 when mc starts to boot up. not sure if a bit of code got overlooked or a mod incompatibility.

Iceberg-1.19.4-forge-1.1.9.jar works as intended

im on mc 1.19.4

forge 45.0.57

[launcher_log](https://mclo.gs/7dWed64)

[debug](https://mclo.gs/tyzCxDc)

[latest](https://mclo.gs/vKSZ0j5)

mods used:

[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Endless Biomes (by MadoctheHadoc)](https://www.curseforge.com/minecraft/mc-mods/endless-biomes)
[BlockUI (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/blockui)
[Mo' Glowstone Lamps (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone-lamps)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Many More Advancements (by Krzychowskyyyy)](https://www.curseforge.com/minecraft/mc-mods/many-more-advancements)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Fantasy's Furniture (by ApexMdr)](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture)
[MVS - Moog's Voyager Structures (by finndog_123)](https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures)
[Storage Racks (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/storage-racks)
[Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
[CTD Core (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/ctd-core)
[Immersive Weapons (by AnonymousHacker1279)](https://www.curseforge.com/minecraft/mc-mods/immersive-weapons)
[Infused Foods (by ApexMdr)](https://www.curseforge.com/minecraft/mc-mods/infused-foods)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Reap Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/reap-mod)
[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Domum Ornamentum (by OrionOnline)](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)
[GravelMiner (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/gravelminer)
[Bad Wither No Cookie - Reloaded (by Kreezxil)](https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded)
[The Aether (by TheAetherTeam)](https://www.curseforge.com/minecraft/mc-mods/aether)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Corail Pillar (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-pillar)
[Security Craft (by Geforce132)](https://www.curseforge.com/minecraft/mc-mods/security-craft)
[Immersive structures (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/immersive-structures)
[Vanilla Plus Tools (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/vanilla-tools)
[Immersive Structures II: Nether edition (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/immersive-structures-ii-nether-edition)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Oreberries Replanted (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/oreberries-replanted)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Fish of Thieves (by SteveKunG)](https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves)
[TieFix (by j_t_a_i)](https://www.curseforge.com/minecraft/mc-mods/tiefix)
[Unseen World (by sashakyotoz)](https://www.curseforge.com/minecraft/mc-mods/unseen_world)
[Skin Layers 3D (Fabric/Forge) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Structure Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)
[Borderless Window (by nekeras)](https://www.curseforge.com/minecraft/mc-mods/borderless)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Creeper Firework (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/creeper-firework)
[Savage Ender Dragon[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/savage-ender-dragon)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Canary (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/canary)
[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Cristel Lib (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/cristel-lib)
[AmbientSounds 5 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[FPS Monitor (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/fps-monitor)
[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
[Ultris: Boss Expansion (by limesplatus)](https://www.curseforge.com/minecraft/mc-mods/ultris-boss-expansion)
[Ad Astra (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[FLIB (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/flib)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[MineColonies (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/minecolonies)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Advancement Plaques [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)
[Ender Mail (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/ender-mail)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Packed Up (Backpacks) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/packed-up-backpacks)
[ESSENTIAL Mod (by SparkUniverse_)](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[Corail Woodcutter (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)
[The Undergarden (by Quek04)](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)
[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Multi-Piston (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/multi-piston)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Structurize (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/structurize)
[Stylecolonies (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/stylecolonies)
[Large Ore Deposits (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Forbidden and Arcanus (by cesar_zorak)](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)
[Physics Mod (by haubna)](https://www.curseforge.com/minecraft/mc-mods/physics-mod)
[Game Menu Mod Option [Forge] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption)
[Neat (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/neat)
[Cooking for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)
[TrashSlot (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/trashslot)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Transparent (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/transparent)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Eccentric Tome (by EccentricVamp)](https://www.curseforge.com/minecraft/mc-mods/eccentric-tome)
[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
[Inventory Essentials (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/inventory-essentials)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[Fast Portals (by gluegunner4)](https://www.curseforge.com/minecraft/mc-mods/fast-portals)
[Portable Crafting Table (by 00theblackwolf00)](https://www.curseforge.com/minecraft/mc-mods/portable-crafting-table)
[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Unstructured [Fabric/Forge] (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/unstructured)
[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[The Lost Cities (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-lost-cities)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[The One Probe (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-one-probe)
[Rapid Leaf Decay (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/rapid-leaf-decay)
[Advent of Ascension (Nevermine) (by Scimiguy)](https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[Mo' Glowstone (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone)
[Exotelcraft (by TKD_Kedis)](https://www.curseforge.com/minecraft/mc-mods/exotelcraft)
[Ash API (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/ash-api)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Chisels & Bits - For Forge (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/chisels-bits)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[Clickable advancements[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/clickable-advancements)
[Additional Banners (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/additional-banners)
[Biome Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/biome-music)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Why stacks of 16? (by LaidBackSloth42)](https://www.curseforge.com/minecraft/mc-mods/why-stacks-of-16)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Enhanced Farming (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-farming)
[Wormhole (Portals) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/wormhole-portals)
[Just Another Rotten Flesh to Leather Mod (by alexdaum1)](https://www.curseforge.com/minecraft/mc-mods/just-another-rotten-flesh-to-leather-mod)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Immersive Weapons Compatibility Bridge (by AnonymousHacker1279)](https://www.curseforge.com/minecraft/mc-mods/immersive-weapons-compatibility-bridge)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Blue Skies (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/blue-skies)
[Ad Astra!: Giselle Addon (by 지젤쟝다)](https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon)
[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)
[Re-chiseled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)

**Comment by AHilyard** [comment]
This line in your latest.log file explains the issue: `[03Jun2023 12:13:20.679] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'iceberg', Expected range: '[45.0.64,)', Actual version: '45.0.57'`
The latest version of Iceberg requires at least Forge 45.0.64.
