### ISSUE TITLE
1.20.1 Render Crash

### ISSUE THREAD

**Issue by GangstaPichu** [AHilyard/Iceberg#38]
A renderer crashed happened with a Golden Enchanted Sword I got out of a portal chest.

[https://mclo.gs/LWosviO](url)

**Comment by Randomsito** [comment]
I have the same problem. The only mod I have related to iceberg is legendary tooltips.
Here is the crash report: https://mclo.gs/2kr9xpO

**Comment by AHilyard** [comment]
This has been fixed in the latest version of Iceberg (1.1.12).  😄
