### ISSUE TITLE
crashes the game

### ISSUE THREAD

**Issue by Gryem** [AHilyard/Iceberg#40]
I have the latest version of iceberg and modmenu installed, when i try to change a mods setting in modmenu it crashes my game and gives me this error:
The game crashed whilst rendering screen
Error: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_332::method_51435(Lnet/minecraft/class_327;Ljava/util/List;IILnet/minecraft/class_8000;)V has incompatible changes at opcode 225 in callback iceberg.mixins.json:GuiGraphicsMixin from mod iceberg->@Inject::storeLocals(Lnet/minecraft/class_327;Ljava/util/List;IILnet/minecraft/class_8000;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IIIILorg/joml/Vector2ic;)V.

**Comment by AHilyard** [comment]
This has been fixed in the latest version, just released.  Enjoy! 😄
