### ISSUE TITLE
[crash] crash with andromeda during world creation

### ISSUE THREAD

**Issue by dadoirie** [AHilyard/Iceberg#41]
https://mclo.gs/F7zSVns

https://mclo.gs/5250GJ4 (same thing just with the stack deobfuscator mod)

posted this first on andromeda's github: https://github.com/melontini/andromeda/issues/34

UPDATE: this here is actually more worse then imagined: it crashes the client also after entering mod settings - not all mods & and only when andromeda is present
it crashes when accessing mod menu settings from andromeda and itemswapper mods

**Comment by AHilyard** [comment]
Version 1.1.15 has been released which fixes this crash, enjoy. 😄
