### ISSUE TITLE
Weird singleplayer crash [1.20.2]

### ISSUE THREAD

**Issue by Taiyou06** [AHilyard/Iceberg#52]
https://mclo.gs/QlShhB7

It seems it's PlayerAdvancementsMixin related.

**Comment by tashaschmidt** [comment]
I'm having the same issue.

**Comment by Anoaxx** [comment]
up

**Comment by AHilyard** [comment]
Hey everyone, just wanted to let you know that I have ported Iceberg to 1.20.2 as of a few days ago.  This should resolve the issues you were having.
