### ISSUE TITLE
Problem with mod create tooltip

### ISSUE THREAD

**Issue by 0Trinster0** [AHilyard/Iceberg#56]
I have checked when putting and removing the mod, the iceberg library generates this aesthetic error in the tooltip of create, can you fix it? I would appreciate it very much
![2023-11-10_17 56 11](https://github.com/AHilyard/Iceberg/assets/150207340/cdb267d8-edd7-45ce-bca1-763ef6b43d56)

**Comment by AHilyard** [comment]
Duplicate of #17.  Hopefully will be fixed soon by Create (See linked PR).
