### ISSUE TITLE
1.20.2 Forge conflict with SuperMartijn642sCoreLib

### ISSUE THREAD

**Issue by Wiseclone** [AHilyard/Iceberg#59]
Conflicts with SuperMartijn642sCoreLib. Client will not start with both mods active.
[crash-2023-12-03_18.26.37-client.txt](https://github.com/AHilyard/Iceberg/files/13541682/crash-2023-12-03_18.26.37-client.txt)
See attached logs for details.

**Comment by AHilyard** [comment]
Thank you for your report, I've been discussing this with SuperMartijn642 and this seems like a fairly new conflict.  We are exploring different solutions, I will update this issue when we've resolved it.

**Comment by AHilyard** [comment]
This has been resolved in the latest version of SuperMartijn642sCoreLib.  Thank you for the report! 😄
