### ISSUE TITLE
[BUG] Crash with Configured

### ISSUE THREAD

**Issue by MrHimera** [AHilyard/Iceberg#65]
Minecraft 1.20.1
Forge: 47.2.20
Iceberg 1.1.18
Configured 2.2.2

The game crashes when launching with the Configured mod.

**Comment by AIRLord19** [comment]
Same problem

**Comment by Barerock** [comment]
Same

**Comment by Qee1y** [comment]
same+1

**Comment by AHilyard** [comment]
This has been fixed in version 1.1.21.  Enjoy! 😄
