### ISSUE TITLE
Iceberg Issue for Minecraft 1.18.2

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [AHilyard/Iceberg#8]
**Describe the bug**
**I believe that Iceberg 1.18.1 is not compatible with Minecraft 1.18.2.**

**To Reproduce**
**1. Download Iceberg
2. Put to mods folder
3.  Run with fabric loader**

**Expected behavior**
**I expect it to run properly but it breaks on startup.**

**Screenshots**

**Environment (please complete the following information):**
 - Mod name: **Iceberg**
 - Mod version: **1.18.1**
 - Modloader: **Fabric**
 - Modloader version: [Include both Fabric version and Fabric API version if using Fabric]
 **fabric-api-0.47.8+1.18.2 + fabric loader 0.13.3 v1.18.2**
 - Minecraft version: **1.18.2**
**Log files**
Please attach your latest.log file as a file attachment, that was generated when the problem occured.  If a crash is occurring, also attach your crash log file as a file attachment.
[latest.log](https://github.com/AHilyard/Iceberg/files/8187860/latest.log)

**Additional context**
Add any other notes or context about the problem here.  e.g. If it worked previously, what changed about your setup?  Are you playing single player or multiplayer?  Etc.

**Comment by AHilyard** [comment]
Thanks for the report.  This has been fixed in the latest update to Iceberg, enjoy! :)
