### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by Reshy** [AHilyard/Iceberg#9]
**Describe the bug**
Crashes when using it in a modpack.

**To Reproduce**
1. Load the game.

**Expected behavior**
Shouldn't crash.

**Environment (please complete the following information):**
 - Mod name:  Iceberg
 - Mod version:  Iceberg-1.18.2-1.0.43.jar
 - Modloader: Forge
 - Modloader version: 4.1.20
 - Minecraft version:  1.18.2

**Log files**
Latest:  https://pastebin.com/Az5UQFhv

Crash:  https://pastebin.com/ENBqBDBr

**Comment by AHilyard** [comment]
Thank you for the report.  I have just fixed this in version 1.0.44, it should be available now.
